# Examen Segundo Parcial

In [1]:
# Your imports HERE !!!!
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from os import path

ModuleNotFoundError: No module named 'matplotlib'

## 01 - Anotaciones - 1 pt

El diccionario `players` contiene el nombre y la estatura de los miembros de un equipo de la NBA. Hacer un gráfico de línea donde el eje x sea una enumeración (una entrada por jugador, es decir, su posición en la lista de nombres), el eje y la estatura, y que contenga anotaciones de flecha donde se indique el jugador más alto y el más bajo. El texto de las anotaciones es el nombre del jugador correspondiente.

Posible resultado:

<img src="nba_heights.png">

In [ ]:
players = {
    "Nombre": ["LeBron James", "Anthony Davis", "D'Angelo Russell", "Austin Reaves", "Jarred Vanderbilt", "Jaxson Hayes", "Rui Hachimura", "Spencer Dinwiddie", "Christian Wood", "Gabe Vincent", "Max Christie", "Cam Reddish"],
    "Estatura": [2.06, 2.08, 1.93, 1.96, 2.03, 2.11, 2.03, 1.96, 2.08, 1.91, 1.96, 2.01]
}

In [ ]:
# Your solution HERE !!!!
#Ids jugadores

## 02 - En varias líneas - 1 pt

A continuación se presenta la función lambda `oneline_function`. Hacer una función `readable_function` que haga exactamente lo mismo, pero que el código se escriba de forma legible y utilizando estructuras de control clásicas.

In [ ]:
# Your solution here

In [ ]:
# Test Use Case
import random

iterations = 20
oneline_function = lambda i: sum([random.randint(1,20) if n%2 == 0 else random.randint(-20,-1) for n in range(i)])

random.seed(7788)
expected_output = oneline_function(iterations) # This calls the lambda function named oneline_function

# random.seed(7788)
# output = readable_function(iterations) # This calls your function named readable_function

print(expected_output)
# print(output)

# assert(expected_output == output) # This will fail if the data is wrong

## 03

- Escribe una función que reciba un DataFrame, le agregue una nueva columna llamada ‘Promedio’ que sea el promedio de sus columnas Luego, filtre las filas donde el valor de ‘Promedio’ sea mayor que 5 y lo ordene por la columna ‘Promedio’ en orden descendente.

In [ ]:
# your solution here

In [ ]:
# Test Use Case
source_dataframe = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 7, 6], 'C': [7, 12, 9]})
expected_dataframe = pd.DataFrame({'A': [2, 3], 'B': [7, 6], 'C': [12, 9], 'Promedio':[7.0, 6.0]})

output = func_mean(source_dataframe) # This calls your function named func_mean

display(expected_dataframe)
display(output)

assert(expected_dataframe.equals(output)) # This will fail if the dataframe is wrong

## 03 - 1.25pt

- Dado el siguiente DataFrame, reemplaza los valores nulos en la columna ‘B’ con la media de los valores de esa columna. Luego, normaliza los valores de la columna ‘C’ para que estén en el rango [0, 1].

In [1]:
#your solution here

In [8]:
# Test Use Case
source_dataframe = pd.DataFrame({'A': [1, 2, 3], 'B': [4, None, 6], 'C': [7, 8, 9]})
expected_dataframe = pd.DataFrame({'A': [1, 2, 3], 'B': [4.0, 5.0, 6.0], 'C': [0, 0.5, 1.0]})

def func(df):
    df = df.copy()
    meanB = df["B"].mean()
    df["B"] = df["B"].fillna(meanB)

    minC = df["C"].min()
    maxC = df["C"].max()
    df["C"] = (df["C"] - minC) / (maxC - minC)

    return df
    
output = func(source_dataframe) # This calls your function named func

display(expected_dataframe)
display(output)

assert(expected_dataframe.equals(output)) # This will fail if the dataframe is wrong

   A    B    C
0  1  4.0  0.0
1  2  5.0  0.5
2  3  6.0  1.0

   A    B    C
0  1  4.0  0.0
1  2  5.0  0.5
2  3  6.0  1.0